### ISSUE TITLE
License TBD?

### ISSUE THREAD

**Issue by triptych** [bookiza/bookiza.js#6]
If you want folks to use your work, it's really important that they know what the license is. Can you clarify?

**Comment by marvindanig** [comment]
One of the reasons I have been reluctant on choosing standard FOSS licensing is the fact that most of the available options are _pro corporate_. Or at least they are designed in a way that corporations can easily use those options to kill competition and individual projects and project themselves as someone who is pro open-source and all that. You know what I mean.  

I know this is also somewhat a sacrilege to say, but I think we need a better alternative licensing model (and I'm no expert here) according to our reality in 2019 so that projects like this one that are a marathon of an individual developer like me can sustain without worrying about how the food will be put on the table. And yes, I have spent four years developing this project from scratch thinking up, testing and evaluating the specification to find what works from what doesn't. Most of this work has been borderline _standards level_ engineering and even now not everything is solved nor rolled-out in the open for a simple reason that I'm confused about what I'm doing in life.  

--- 

This whimsical note aside, I am actually still open to licensing under MIT as long as I'm not forced to raise money from crap investors, beg for donation or die supporting ecosystem held by a large corporation. I have a couple of ideas around this but I wish to hear what other takes are first.

**Comment by marvindanig** [comment]
> [Blue Oak License](https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html).

I'm considering the BlueOak License for this project, will update the repos shortly.

**Comment by sskras** [comment]
> I'm considering the BlueOak License for this project, will update the repos shortly.

Nice to hear:)

BTW, I just registered a https://github.com/licensee/licensee/issues/379 . I am trying to make it into Github's license list.
